import imgApi from '../images/photos';
import r1 from '../../api/apps/r1.jpg';
import r2 from '../../api/apps/r2.png';
import r3 from '../../api/apps/r3.jpg';
import r4 from '../../api/apps/r4.jpg';
import r9 from '../../api/apps/r9.jpg';
import r10 from '../../api/apps/r10.jpg';
const productData = [
  {
    id: '1',
    name: 'Practice exercises',
    thumbnail: r1,
    desc: 'Chapter 1 practice exercises for 7AChapter 1 practice exercises for 7A.',
    ratting: 4,
    price: 30,
    prevPrice: 0,
    discount: '',
    soldout: false,
  },
  {
    id: '2',
    name: 'Theory review',
    thumbnail: r2,
    desc: 'Theory compilation and sample exercises for 8C.',
    ratting: 0,
    price: 15,
    prevPrice: 150,
    discount: '90%',
    soldout: false,
  },
  {
    id: '3',
    name: 'Video lectures',
    thumbnail: r3,
    desc: 'Video lecture from chapter 1 to chapter 10 for 8D',
    ratting: 5,
    price: 30,
    prevPrice: 0,
    discount: '',
    soldout: true,
  },
  {
    id: '4',
    name: 'Suggestions for presentation',
    thumbnail: r4,
    desc: 'Suggested topics for class 7D',
    ratting: 2,
    price: 80,
    prevPrice: 100,
    discount: '20%',
    soldout: false,
  },
  {
    id: '5',
    name: 'Suggestions for presentation',
    thumbnail: r9,
    desc: 'Suggested topics for 8F',
    ratting: 5,
    price: 50,
    prevPrice: 0,
    discount: '',
    soldout: false,
  },
  {
    id: '6',
    name: 'Practice exercises for chapter 6',
    thumbnail: r1,
    desc: 'Chapter 6\'s exercises for 8F',
    ratting: 4,
    price: 75,
    prevPrice: 100,
    discount: '25%',
    soldout: false,
  },
  {
    id: '7',
    name: 'Difficult exercises',
    thumbnail: r10,
    desc: 'This exercises only assign for good student in grade 8.',
    ratting: 5,
    price: 20,
    prevPrice: 16,
    discount: '20%',
    soldout: false,
  },
  {
    id: '8',
    name: 'Video lectures',
    thumbnail: r3,
    desc: 'Video about chapter 9 & 10 for 7B.',
    ratting: 1,
    price: 30,
    prevPrice: 0,
    discount: '',
    soldout: false,
  },
  {
    id: '9',
    name: 'Practice exercises',
    thumbnail: r1,
    desc: 'Chapter 2 practice exercises for 7D',
    ratting: 4,
    price: 50,
    prevPrice: 100,
    discount: '50%',
    soldout: false,
  },
  {
    id: '10',
    name: 'Practice exercises',
    thumbnail: r1,
    desc: 'Chapter 1 practice exercises for 8A.',
    ratting: 5,
    price: 30,
    prevPrice: 0,
    discount: '',
    soldout: true,
  },
  {
    id: '11',
    name: 'Practice exercises',
    thumbnail: r1,
    desc: 'Chapter 1 practice exercises for 8B.',
    ratting: 4,
    price: 66,
    prevPrice: 200,
    discount: '67%',
    soldout: false,
  },
];

export default productData;
